POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "user2",
    "password": "password2"
}

###

POST http://localhost:8000/customer/login
Content-Type: application/json

{
    "username": "user2",
    "password": "password2"
}

###


PUT http://localhost:8000/customer/auth/review/1
Content-Type: application/json

{
    "review" : "new review by me"
}

###

PUT http://localhost:8000/customer/auth/review/1
Content-Type: application/json

{
    "review" : "new review by me2"
}


###


GET http://localhost:8000/review/1
Content-Type: application/json
